version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "aws-java-example"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4lernl3iuwdl"
s3_prefix = "aws-java-example"
region = "us-east-1"
profile = "main"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
